version: 2
jobs:
  build:
    working_directory: /workflowr
    docker:
      - image: rocker/r-apt:bionic
    branches:
      only:
        - master
        - dev
        - circleci
    steps:
      - checkout
      - run:
          name: Install devtools
          command: |
            apt-get update
            apt-get install -y r-cran-devtools r-cran-stringr
      - run:
          name: Install package dependencies
          command: r -e "devtools::install_deps(dependencies = TRUE, upgrade = FALSE)"
      - run:
          name: Build and check
          command: bash build.sh --no-examples --no-manual
      - store_artifacts:
          path: workflowr.Rcheck/
